### ISSUE TITLE
Mounted with Skyriding taking priority over mounted while using a ground only mount.

### ISSUE THREAD

**Issue by JSON-135** [mpstark/DynamicCam#100]
So im having an issue while im using a ground mount the sitation "Mounted with Skyriding" is taking priority even though i am mounted on a ground mount. This making my custom settings i want to use for grounded mounts not take affect because of the mounted with skyriding situation. Even though it is not skyriding capable.

**Comment by LudiusMaximus** [comment]
Got you! :-)

I will make the following 8 situtations, which should be sufficient for any possible setup:

Mounted (any)                                      
Mounted (only flying-mount)                        
Mounted (only flying-mount airborne)               
Mounted (only flying-mount airborne Skyriding-on)  
Mounted (only flying-mount Skyriding-on)           
Mounted (only airborne)                            
Mounted (only airborne Skyriding-on)               
Mounted (only Skyriding-on)                        

Give me 1-2 days. :-)

**Comment by JSON-135** [comment]
Thank you much! This would be great for those that still run around on ground mounts, especially for RP purposes while being able to have a pretty camera situation.

**Comment by LudiusMaximus** [comment]
It is done with the new version 2.8.0. Let me know how you like it.
