### ISSUE TITLE
DynamicCam Importing / Export Profile not available 

### ISSUE THREAD

**Issue by Ryuzoji** [mpstark/DynamicCam#101]
DynamicCam won't let me import or export any profile it says Coming soon (TM) 

![image](https://github.com/user-attachments/assets/d3c1c995-f524-41fb-a249-4b5ae325f4f2)

![image](https://github.com/user-attachments/assets/70bed9df-1936-4ef6-a40e-f24841a1a5c3)

**Comment by LudiusMaximus** [comment]
Yeah, I still haven't gotten around to implementing that thing. Two years ago, the entirety of DynamicCam had to be revamped, which also required to redo the import/export functions. In the end of August I will have two weeks off. Hopefully I can do it then.
