### ISSUE TITLE
DynamicCam v2.8.1 Error report: (Situation: Mounted (only airborne + Skyriding).Condition Script)

### ISSUE THREAD

**Issue by kaiiboraka** [mpstark/DynamicCam#104]
Error Message:

Error: Mounted (only airborne + Skyriding) (106), condition, runtime

Interface/AddOns/DynamicCam/SituationManager.lua:1009: attempt to call global 'UnitBuff' (a nil value)

**Comment by jeansteffano** [comment]
I got the same error:

Error: Mounted (only Skyriding) (107), condition, runtime

Interface/AddOns/DynamicCam/SituationManager.lua:1009: attempt to call global 'UnitBuff' (a nil value)

**Comment by LudiusMaximus** [comment]
Thanks for reporting. Should be fixed with release 2.8.2.
