### ISSUE TITLE
error report!

### ISSUE THREAD

**Issue by zeebea** [mpstark/DynamicCam#105]
Error: Dracthyr Soar (120), condition, runtime

[string "for i = 1, 40 do..."]:2: attempt to call global 'UnitBuff' (a nil value)

got this when i logged in after updating to the latest dynamic cam patch
i think i remember the issue being fixed in the latest update, but just wanted to check what i should do since it instructed me to copy the error message here!

edit: got this one too

Error: Mounted (only Skyriding) (107), condition, runtime

Interface/AddOns/DynamicCam/SituationManager.lua:1009: attempt to call global 'UnitBuff' (a nil value)

i havent updated my settings since before the update that fixed dracthyr soar, so Im sure that's all it is
but just in case i'll update the post if i get any more messages!

**Comment by LudiusMaximus** [comment]
Thanks for reporting! Should work again with release 2.8.3.
