### ISSUE TITLE
Error report - 'GetSpellInfo' (a nil value)

### ISSUE THREAD

**Issue by FrancisMT** [mpstark/DynamicCam#106]
Got the following error after logging in after updating to the latest dynamic cam patch:

```
Error: Fishing (302), condition, runtime

[string "return UnitChannelInfo("player") == GetSpel..."]:1: attempt to call global 'GetSpellInfo' (a nil value)

```

I checked and the condition script is the following:
`return UnitChannelInfo("player") == GetSpellInfo(7620)`

**Comment by LudiusMaximus** [comment]
Thanks for reporting. Should be fixed with release 2.8.2.
