### ISSUE TITLE
Shoulder offset not working after lastest update

### ISSUE THREAD

**Issue by FrancisMT** [mpstark/DynamicCam#107]
After logging in after updating to the latest dynamic cam patch, I noticed that the "Camera Over Shoulder Offset" is no longer working.

Independently of the value that I choose (normally -2 to move my characters to the right side of the screen), the offset does not change ingame.

I checked and the cvar "test_cameraOverShoulder" is holding the value that I set via the addon settings (-2), but to no effect.

**Comment by LudiusMaximus** [comment]
It works for me after I resolved other issues introduced with 11.0.2. Thanks for reporting!

**Comment by Thuuna** [comment]
Same Problem.
HorizontalOffset stays on Default, doesnt matter the parameter.
