### ISSUE TITLE
On login to a Prot  Warrior

### ISSUE THREAD

**Issue by MasterRanger** [Mpstark/DynamicCam#11]
Date: 2018-08-16 16:38:00
ID: 1
Error occured in: Global
Count: 1
Message: [string "for k,v in pairs(this.buffs) do ..."] line 2:
   Usage: UnitBuff("unit", [index][, "filter"])
Debug:
   [C]: UnitBuff()
   [string "for k,v in pairs(this.buffs) do ..."]:2: in main chunk
   (tail call): ?
   DynamicCam\Core.lua:775: ?()
   Ace3\AceTimer-3.0\AceTimer-3.0.lua:55:
      Ace3\AceTimer-3.0\AceTimer-3.0.lua:50
Locals:
(*temporary) = "player"
(*temporary) = "Bladestorm"
(*temporary) = nil
(*temporary) = 236303
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 46924

AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  Ace3, v
  ACP, vr259 
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  BlizzMove, vv1.8
  CanIMogIt, v8.0.0v1.11
  Chatter, v1.5.8
  DBMCore, v8.0.3
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  Dominos, v8.0.6
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  DynamicCam, vBeta 4
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  GatherMate2, v1.43
  ILDBlizzard, v2.1.2 70200
  ILDOnebag3, v2.1.2 70200
  Informant, v7.7.6000 (SwimmingSeadragon)
  ItemLevelDisplay, v2.1.2 70200
  LibSharedMedia30, v3.0-104
  Mapster, v1.8.0
  OmniCC, v8.0.1
  OneBag3, vv3.10.1
  OneBank3, vv3.9.1
  OneCore, vv1.8.1
  PitBull4, vv4.1.14
  Postal, vv3.6.0
  Quartz, v3.4.0
  SellJunk, v3.0.15
  SexyMap, vv8.0.8
  Skada, v1.7.5
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  Stubby, v7.7.6000 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v9.0.10
  TipTac, v18.08.12
  TipTacItemRef, v18.08.12
  TipTacTalents, v18.07.30
  Titan, v5.14.3.80000
  TitanBag, v5.14.3.80000
  TitanClock, v5.14.3.80000
  TitanGold, v5.14.3.80000
  TitanLocation, v5.14.3.80000
  TitanLootType, v5.14.3.80000
  TitanPerformance, v5.14.3.80000
  TitanRepair, v5.14.3.80000
  TitanSpeed, v7.3.001
  TitanVolume, v5.14.3.80000
  TitanXP, v5.14.3.80000
  TomTom, vv80001-1.0.2
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=723)

**Comment by LudiusMaximus** [comment]
Not sure if this is still an issue. I cannot reproduce it.
