### ISSUE TITLE
Skyriding Situation Frametime Stuttering

### ISSUE THREAD

**Issue by V1rtuou5** [mpstark/DynamicCam#113]
Situations with "Skyriding" in name are causing consistent .5 sec frametime stutters from their "Condition Scripts" <img width="2294" alt="Wow_2024_08_26_22_28_02_189" src="https://github.com/user-attachments/assets/3bf070e7-4e9f-4550-8741-c03c21148f1b">
![Skyriding Script Disabled](https://github.com/user-attachments/assets/1c7fa9ba-30e2-4fd7-9f7d-2d8f55450fee)
![Skyriding Situations](https://github.com/user-attachments/assets/efa28758-d848-441d-8dc9-44054d261bbe)

**Comment by LudiusMaximus** [comment]
Thanks a lot for reporting! The new release 2.9.0 should have resolved these performance issues.
