### ISSUE TITLE
After dismounting the camera jumps fast from left to centre and than moves back left. 

### ISSUE THREAD

**Issue by skipabeat123** [mpstark/DynamicCam#120]
https://github.com/user-attachments/assets/0bcefef7-315b-41d4-bc9c-c177f2701abd

This happens when horizontal offset is set to 2.8, but when its a negative value (character to the right from the centre of the screen) this movement does not happen. I'm using a clean install out of the box addon.

**Comment by LudiusMaximus** [comment]
I fell you. Unfortunately, this is just how the shoulder offset is (wrongfully) implemented in WoW. It has a different effect depending on the mount or even on the player model (e.g. druid forms, worgen, etc.).

I started another addon to automatically compensate this, but it is sometimes difficult to guess the correct time at which to apply the new offset value. For mounting and dismounting, however, it works most of the times without annoying camera jerks.
Check it out, if you like: https://www.curseforge.com/wow/addons/cameraovershoulder-fix-dynamiccam
