### ISSUE TITLE
Problem with a Heart/Teleport Condition Script issue?

### ISSUE THREAD

**Issue by ZaViper** [mpstark/DynamicCam#121]
After the latest update after logging in I get a window that pops-up saying something like:

There is a problem with your DynamicCam Situation Controls.
>then it goes on to say this error is caused by the default settings of a DynamicCam stock situation and to copy a code and send to you<

And this is the code that it tells me to send to you:

Error: Hearth/Teleport (200), condition, runtime

[string "local _, _, _, _, _, _, _, _, spellId  = Un..."]:2: attempt to index field 'teleportSpells' (a nil value)

**Comment by LudiusMaximus** [comment]
It seems to me that you are not using the stock initialisation script for this situation.
It will tell you so by the orange colour:
![image](https://github.com/user-attachments/assets/68afd7f5-9905-4f95-863e-a94a6a87c7da)
If so, press the "Restore stock setting" button.

You can also check the "About" tab in DynamicCam, which will tell you if you have custimised your situations:
![image](https://github.com/user-attachments/assets/8cb67977-491f-4e63-9023-d7d9cf1e8f7e)

Let me know if this was the issue.

**Comment by ZaViper** [comment]
Yes this cleared it up. Although this also removed the spell ids I added for another items not in the default list like the Wormhole toys, tabards that can teleport, jaina's locket, etc. Will it cause issues if I added them back in?

**Comment by LudiusMaximus** [comment]
Good to hear! :-) No, I just changed the variable names. You adding extra spells will not break it.
Or why do you not just tell me the spellIDs, so I can add them to the code for everyone?

**Comment by ZaViper** [comment]
Sure!

448126 = Wormhole Generator: Khaz Algar
324031 = Wormhole Generator: Shadowlands
163830 = Wormhole Centrifuge
250796 = Wormhole Generator: Argus
299083 = Wormhole Generator: Kul Tiras
126755 = Wormhole Generator: Pandaria
67833 = Wormhole Generator: Northrend
299084 = Wormhole Generator: Zandalar
73324 = Jaina's Locket
66238 = Argent Crusader's Tabard
89597 = Baradin's Wardens Tabard
89598 = Hellscream's Reach Tabard
49844 = Direbrew's Remote
175608 = Relic of Karabor
41234 = Blessed Medallion of Karabor
36890 = Dimensional Ripper - Area 52
23442 = Dimensional Ripper - Everlook
36941 = Ultrasafe Transporter: Toshley's Station
23453 = Ultrasafe Transporter: Gadgetzan
291981 = Ultrasafe Transporter: Mechagon

I might be missing more. I'm currently not on WoW at the moment to see what items I had, but I feel like this is the most of them.

**Comment by LudiusMaximus** [comment]
Thanks, I included these in the new release 2.9.2.
Let me know, if you have more teleport spells to add. :-)
