### ISSUE TITLE
Completing Skyrider Racing close up camera

### ISSUE THREAD

**Issue by Krekot** [mpstark/DynamicCam#126]
Like in title, after skyriding race camera close up really close even when I have set up everything to max range.

https://www.youtube.com/watch?v=dEdnQJPwtV8

**Comment by LudiusMaximus** [comment]
Hi, please try what happens if you set "restore zoom" to "never" in all the involved situations. If "restore zoom" is enabeld, restoring the last zoom when returning to a previous situation overrides this situation's zoom setting.

**Comment by Krekot** [comment]
That worked. Thanks!!!
