### ISSUE TITLE
Help creating a custom situation

### ISSUE THREAD

**Issue by Auranim** [Mpstark/DynamicCam#13]
Hi :D I have zero coding skills, so if possible, I'd like some help creating a custom situation. Should be fairly straightforward: whenever my character is channelling a spell, activate the situation. The spell in question is Eagle Eye. I don't like how close it gets to the ground when cast, so I'd like to pull the zoom all the way up for whenever I'm channelling and then return to the previous situation when I'm done. Is it possible?

**Comment by LudiusMaximus** [comment]
Sorry, I have no experience in that. Maybe you better ask such a question in the curseforge forum, where other users can maybe help you. These github issues here should probably rather be used for bug reports.

**Comment by Auranim** [comment]
Thanks, will do o/
