### ISSUE TITLE
Camera displacement

### ISSUE THREAD

**Issue by Smerdokryl** [Mpstark/DynamicCam#15]
Sometimes after jumping (or, rather, landing), when you go back to land after diving, and also after death, the camera ends up focused on the character's waist. I tried to mess around with dynamiccam settings, but the camera position is only restored after a /reload.

**Comment by LudiusMaximus** [comment]
Are you still having this issue? If so, could you upload your config file:
World of Warcraft\_retail_\WTF\Account\<your account>\SavedVariables\DynamicCam.lua

**Comment by LudiusMaximus** [comment]
No answer from OP...
