### ISSUE TITLE
Druid flight/travel form is not being considered as a mount

### ISSUE THREAD

**Issue by nekron** [Mpstark/DynamicCam#3]
It loads the default situation for that area instead of the mounted situation.

I know you said this in the forums:

>I will likely make a separate situation for travel form and other spells like it because you can use them in combat and you would want the combat situations to take priority.
>
>Right now the Mounted "situation" are higher in priority than the combat situations because that makes sense because when you're mounted, you don't want to swap because some mob aggro'd on you while you were running through.

Just wanted to track it as a GitHub issue so others can see its progress.

I'll try to take a look at your code so I can send you a PR, but I'm not used to coding in lua, and I've never done any wow add-ons either. I tend to separate work from pleasure 😛

**Comment by Lutwick** [comment]
Hm, apparently Mpstark was not hit by a bus -- which is good to know :-) -- because he has recently been active on his new Battletech project.

But what about the future of dynamicCam? I think there are a lot of people out there who are using and very much appreciating it...

**Comment by nekron** [comment]
I believe that in this kind of scenario, where the owner doesn't have the time to continue with the project, the best thing to do is to invite someone else as a collaborator. Someone that can keep in touch wit him and knows his goals and milestones and can carry on with that in mind. Accepting PRs and making new releases without loosing focus of that goals.

I think it's better than the alternative, where someone else forks the project and releases a new version without consulting the original dev. I don't like being that guy.

I don't have the time to carry on with any open source project right now, so I try to contribute here and there when I can.

I'm not entirely sure how (or if) this add-on will work with the new BfA interface and api (haven't played in the ptr).

If we don't hear from @Mpstark before BfA is released, I'm thinking that we may not have other choice but to fork it and continue it ourselves if we want to keep using it. Even if I don't like the idea 😞

**Comment by Lutwick** [comment]
@Mpstark Good to hear from you. That's fair enough.

I agree with @nekron: Let's wait if/how the whole dynamic camera features will be supported in BfA. If they are, it would be nice to build a new release including the flight/travel form fix by @nekron and my shoulder offset fixes.

**Comment by Lutwick** [comment]
All right! The BfA pre-patch is out and people start complaining that DC is not working for them any more...
(https://www.curseforge.com/wow/addons/dynamiccam#c326) What are we going to do...?

**Comment by LudiusMaximus** [comment]
Solved with next release.
