### ISSUE TITLE
Can't SetCVar for flying pov in situation

### ISSUE THREAD

**Issue by jsbursik** [Mpstark/DynamicCam#30]
On my Demon Hunter I've set up a condition that properly activates once the "Glide" aura is applied to my demon hunter (verified by having it hide my UI while the Aura is applied) the problem is I can't seem to set the CVar for test_cameraDynamicPitchBaseFovPadFlying in initialization/enter.

[Here is what my setup looks like.](https://i.imgur.com/SJlTtj5.png)

The reason I am doing this is because glide technically counts as flying as far as actioncam is concerned, and it's annoying having my base pad fov change when I'm gliding through instances. (I could technically just adjust the slider, but flying with a low base pad fov is such a bad experience)

**Comment by LudiusMaximus** [comment]
Yeah, the thing is that DynamicCam resets the default variables at every situation change; unless the situation has another value overriding the default. As situations are at the moment not able to set specific pitch values, you always get the default.

I am working on a new version, in which **all** camera settings can be defined situation specific. This will resolve your issue. But it might take 1-2 weeks until I am done.

For the time being, you coud replace
SetCVar("test_cameraDynamicPitchBaseFovPadFlying", 0.12)
in your OnEnter script with

C_Timer.After(0.05, function() SetCVar("test_cameraDynamicPitchBaseFovPadFlying", 0.12) end)

Then your variable change will come **after** the default restore and should remain effective.

**Comment by jsbursik** [comment]
Gotcha, that fix worked, looking forward to your update! Thanks for making this mod, it's completely changed my WoW experience. I'll close this issue.

**Comment by LudiusMaximus** [comment]
No problem! Glad you like it.
I will leave this open until my new release is finished.

**Comment by LudiusMaximus** [comment]
> I am working on a new version, in which **all** camera settings can be defined situation specific. This will resolve your issue. But it might take 1-2 weeks until I am done.

More like 6-9 months... ;-)
But the changes regarding this issue here are already in the current repository code. So I am closing this.
