### ISSUE TITLE
Disable CameraKeepCharacterCentered cvar

### ISSUE THREAD

**Issue by Ketho** [Mpstark/DynamicCam#31]
Since the "Keep Character Centered" option disables actioncam functionality in patch 9.0.1, can't you just disable it with
```
C_CVar.SetCVar("CameraKeepCharacterCentered", 0)
```

**Comment by LudiusMaximus** [comment]
Thanks! I intend to do this with the next release. But I wanted to give some user feedback while doing so, such that people don't get confused if their accessibility settings are getting reset.
