### ISSUE TITLE
removing addon breaks camera settings

### ISSUE THREAD

**Issue by rodeobear** [Mpstark/DynamicCam#36]
so, tried the addon again after a while, i like the concept but most of the time it just throws me off, and i remembered that as i downloaded and used it for a bit, so i uninstalled it, but now my camera randomly disables the "follow on horizontal movement" option, and only logging out completely fixes it, temporarily, i got rid of the addon files completely but it has somehow altered a base game setting and i cant fix it

**Comment by LudiusMaximus** [comment]
Sorry to hear that. But I have no explanation for this. DynamicCam is not changing anything regarding the horizontal movement or anything. My best guess would be to check if the game's "[Action Cam](https://wow.gamepedia.com/CVar_ActionCam)" is still enabled.

You could try
`/console ActionCam full`
and see if this fixes it.

**Comment by LudiusMaximus** [comment]
After I got another report regarding this, I investigated this further. Here is what I found:
https://www.curseforge.com/wow/addons/dynamiccam?comment=896
