### ISSUE TITLE
What "Smart Pivot Cutoff Distance" means

### ISSUE THREAD

**Issue by OscarStrandmark** [Mpstark/DynamicCam#37]
I think I may have figured out what "Smart Pivot Cutoff Distance" does. It's a minor thing but I still felt like I should post it anyway. The current description made me too curious to not find out. 

When you move your camera into the floor, two things can happen:
1. Your camera will stay in its position but pivot upwards to view the cieling.
2. The camera will slide along the ground and show you a closeup of your characters backside

What "Smart Pivot Cutoff Distance"(SPCD) does is change at what distance these two behaviours will change. Any zoom-value below the SPCD-value will trigger behaviour 2, and any zoom-value above the SPCD-value will trigger behaviour 1.

Example:
![art](https://i.imgur.com/avMmy3g.png)

Let's say SPCD is set to 5, the line in the middle and the theoretical limits on the zoom is from 0-10. 
When the zoom level of the player is lower than that limit. Moving the camera into the ground will trigger behaviour 2. Making it slide it along the ground and zoom on your characters backside.
If the player has their zoom set to larger than the SPCD-value (5), then the camera will instead stay in place and pivot upwards.

I have no idea how to word this in a short enough text to fit into a clear description but I guess now at least you know what it means.

**Comment by OscarStrandmark** [comment]
Damn, I should probably have checked the closed issues first... 🙄

**Comment by LudiusMaximus** [comment]
No worries. I really appreciate this.

But the current version already includes the description:
"Defines the distance that the camera has to be inside of for the ground collision to either bring the camera closer to the character's feet as the camera collides with the ground, or to simply pivot on the spot of camera-to-ground collision."

In the upcoming overhaul I changed this to:
"When the camera collides with the ground, it normally performs an upwards pitch on the spot of the camera-to-ground collision. An alternative is that the camera moves closer to your character's feet while performing this pitch. The 'Smart Pivot Cutoff Distance' setting determines the distance that the camera has to be inside of to do the latter. Setting it to 0 never moves the camera closer (WoW's default), whereas setting it to the maximum always moves the camera closer."

Or why did you have to go and find this out by yourself?

**Comment by OscarStrandmark** [comment]
The tooltip for it in the situations options is still "No idea what this actually does". I was only looking in the situations options, and not in the settings view.

![bild](https://user-images.githubusercontent.com/25204572/101296870-2411ef80-3826-11eb-9762-c52e60510aa2.png)
![bild](https://user-images.githubusercontent.com/25204572/101296876-2f651b00-3826-11eb-992a-b43d4befbd71.png)

**Comment by LudiusMaximus** [comment]
Oh damn. I got to changes this! Thanks for the heads up. ^^
