### ISSUE TITLE
New Mount "Sapphire Skyblazer" is almost off the screen

### ISSUE THREAD

**Issue by Lightfall-Stormrage** [mpstark/DynamicCam#49]
The new mount seems to be broken with the Addon. I use the off-shoulder option as negative (-2.2) and the mounted situation off-shoulder as -1.5. All mounts look okay, but the new mount since I got it today is going absurdly more to the right, as if it was something like -5 and not just -1.5.

**Comment by LudiusMaximus** [comment]
Hi, and thanks for the feedback. What you are describing is no issue of DynamicCam but of how the Wow devs (strangely) implemented the experimental (!) shoulder offset. I have started another add-on to compensate this: https://www.curseforge.com/wow/addons/cameraovershoulder-fix-dynamiccam
