### ISSUE TITLE
Bug: Default Profiles

### ISSUE THREAD

**Issue by lucasvienna** [mpstark/DynamicCam#58]
Had this pop up on the latest v2 alpha:

Error: Hearth/Teleport (200), condition, runtime
```lua
[string "for k,v in pairs(this.spells) do..."]:1: bad argument #1 to 'pairs' (table expected, got nil)
```

**Comment by LudiusMaximus** [comment]
Thanks for the feedback. Is this reproducible or did it only occur once?
If reproducible, what is your init script for the Hearth/Teleport situation?
