### ISSUE TITLE
NPC Interaction excludes event QUEST_PROGRESS

### ISSUE THREAD

**Issue by Jofairden** [Mpstark/DynamicCam#6]
No matter what I've tried, NPC Gossip situation won't trigger if I'm mounted.
Also, the gossip situation is missing the QUEST_PROGRESS event, which I believe should be there.

**Comment by Jofairden** [comment]
Nevermind the first bug, it seems the mounted situation has its priority set to 100 which was completely overriding it obviously. I set it to 10 and now it triggers.

**Comment by Mpstark** [comment]
I've added QUEST_PROGRESS in the trunk build.

**Comment by Jofairden** [comment]
Thanks
