### ISSUE TITLE
Is there a way to disable the "you have enabled one or more experimental camera features" prompt?

### ISSUE THREAD

**Issue by Rycia** [mpstark/DynamicCam#61]
I keep getting a prompt with every UI reload saying "you have enabled one or more experimental camera features."

I deleted all my settings and I managed to get past it before so it would never show up in prep for Dragonflight prepatch and the new UI.

I was able to disable it showing before but I can't find how to do it again.
![image](https://user-images.githubusercontent.com/43384589/197945862-d95e0d7f-01f3-4211-8e7f-d76de1ce2ae9.png)

**Comment by LudiusMaximus** [comment]
If DynamicCam works correctly, this prompt from WoW gets suppressed. Just when you disable DynamicCam or DynamicCam stops functioning (as was the case when 10.0 launched but has been resolved with the latest hotfix) you get this prompt. I guess you experienced this running the non-functioning version of DynamicCam. Please reopen this ticket, if you still have problems. Thanks!
