### ISSUE TITLE
Preset profiles: Immersive and Shushudaa

### ISSUE THREAD

**Issue by hjorim** [mpstark/DynamicCam#62]
I just installed DynamicCam 2 10.0 (fresh install - I didn't have a previous profile or used any previous version of the addon and it's a fresh wow install).

It's giving me this error when trying to load either Immersive and Shushudaa presets:

Error: Hearth/Teleport (200), condition, runtime

[string "for k,v in pairs(this.spells) do..."]:1: bad argument #1 to 'pairs' (table expected, got nil)

When selecting "Fix manually". it leads me to this page:
![image](https://user-images.githubusercontent.com/113323844/199145402-45981303-2e37-4d80-8390-6065d4416fc1.png)

**Comment by LudiusMaximus** [comment]
Yeah, please do not use the profiles in Beta. These are not finished. Sorry, I should have marked that more clearly.
