### ISSUE TITLE
DynamicCam's error message after Elvui AFK screen

### ISSUE THREAD

**Issue by Darkhibaris** [mpstark/DynamicCam#63]
Hi,

Since the first pre-patch update from Dragonflight, I have this error message when I go back from the [afk screen from Elvui.](https://www.youtube.com/watch?v=dPZhQszF6ho&ab_channel=DeadlyDag) I can't see my UI. It can be "fix" when I mount or dismount.

![elvui_AFK_screen](https://user-images.githubusercontent.com/118050158/201469581-d34ff9be-569d-4758-a5c9-375044684bfd.jpg)
![error](https://user-images.githubusercontent.com/118050158/201469565-54a08d6b-f1ae-4738-9dfd-ca2eb98d90dc.jpg)
![Mount_for_fix](https://user-images.githubusercontent.com/118050158/201469778-b739744b-7f65-48ee-b782-619c85e6cfc0.jpg)

------------------------------------------------

270x Interface/AddOns/DynamicCam/UiHideModule.lua:445: Usage: self:SetIgnoreParentAlpha(ignore)
[string "=[C]"]: in function `SetIgnoreParentAlpha'
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:445: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:435>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:475: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:472>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:746: in function `HideUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:653: in function `FadeOutUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:1161: in function `ChangeSituation'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:964: in function `EvaluateSituations'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:163: in function <Interface/AddOns/DynamicCam/Core.lua:153>

Locals:
(*temporary) = Button {
 0 = <userdata>
 glow = Texture {
 }
 OnPostShow = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:4
 SetExternallyManagedOutroAnimation = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:28
 Shield = Frame {
 }
 SetAlertContainer = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:12
 SetAlpha = <function> defined =[C]:-1
 Name = FontString {
 }
 ludius_collected = true
 Background = Texture {
 }
 Icon = Frame {
 }
 GuildBanner = Texture {
 }
 backdrop = Frame {
 }
 waitAndAnimOut = AnimationGroup {
 }
 hooked = true
 GuildBorder = Texture {
 }
 id = 13477
 alertContainer = AlertFrame {
 }
 Unlocked = FontString {
 }
 queue = <table> {
 }
 animIn = AnimationGroup {
 }
 OnManagedAlertFrameVisibilityChanged = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:20
 GetAlertContainer = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:16
 GuildName = FontString {
 }
 OnPostHide = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:8
 ManagesOwnOutroAnimation = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:24
 shine = Texture {
 }
 ludius_ignoreParentAlphaBeforeFadeOut = false
}
(*temporary) = nil

**Comment by Darkhibaris** [comment]
I went back to the version bellow. No problem anymore, but the option's mode doesn't have Y axe value setting. My caracter is too low on my screen now.
![image](https://user-images.githubusercontent.com/118050158/201474157-26ec1edb-a104-47a4-8e6e-f4bd907abcd7.png)

I will wait next addon update to have more option.

**Comment by LudiusMaximus** [comment]
Well, glad it now works with the current DynamicCam-2.0.0.zip. :-)
Let me know, if you are experiencing this issue again. Thanks for reporting it anyway.

**Comment by Darkhibaris** [comment]
With pleasure. Ty for your hard work! This addon is great :)

**Comment by Darkhibaris** [comment]
The problem is back. (version: DynamicCam-2.0.1.zip)
----------------------
1x Interface/AddOns/DynamicCam/UiHideModule.lua:446: Usage: self:SetIgnoreParentAlpha(ignore)
[string "=[C]"]: in function `SetIgnoreParentAlpha'
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:446: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:436>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:476: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:473>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:747: in function `HideUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:653: in function `FadeOutUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:1166: in function `ChangeSituation'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:969: in function `EvaluateSituations'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:163: in function <Interface/AddOns/DynamicCam/Core.lua:153>

Locals:
(*temporary) = Button {
 0 = <userdata>
 ItemName = FontString {
 }
 OnPostShow = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:4
 Label = FontString {
 }
 BGAtlas = Texture {
 }
 SetAlertContainer = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:12
 SetExternallyManagedOutroAnimation = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:28
 hyperlink = "|cff1eff00|Hitem:166846::::::::60:258:::::::::|h[Pièces détachées]|h|r"
 ludius_collected = true
 Background = Texture {
 }
 waitAndAnimOut = AnimationGroup {
 }
 glow = Texture {
 }
 RollValue = FontString {
 }
 RatedPvPBackground = Texture {
 }
 lootItem = Frame {
 }
 RollTypeIcon = Texture {
 }
 UpdateTooltip = <function> defined @Interface/FrameXML/AlertFrameSystems.lua:421
 PvPBackground = Texture {
 }
 queue = <table> {
 }
 animIn = AnimationGroup {
 }
 shine = Texture {
 }
 GetAlertContainer = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:16
 alertContainer = AlertFrame {
 }
 OnPostHide = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:8
 ManagesOwnOutroAnimation = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:24
 OnManagedAlertFrameVisibilityChanged = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:20
 ludius_ignoreParentAlphaBeforeFadeOut = false
}
(*temporary) = nil

**Comment by LudiusMaximus** [comment]
Could you please check if this still happens with 2.0.2, I just uploaded?
Is using Elvui the only way to reproduce this error?
If so, I will check it out over the weekend.

**Comment by Darkhibaris** [comment]
Yes, of course!
The problem remains, sadly.
----------------
1x Interface/AddOns/DynamicCam/UiHideModule.lua:475: Usage: self:SetIgnoreParentAlpha(ignore)
[string "=[C]"]: in function `SetIgnoreParentAlpha'
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:475: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:465>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:505: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:502>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:776: in function `HideUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:669: in function `FadeOutUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:1191: in function `ChangeSituation'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:994: in function `EvaluateSituations'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:163: in function <Interface/AddOns/DynamicCam/Core.lua:153>

Locals:
(*temporary) = Button {
 0 = <userdata>
 ItemName = FontString {
 }
 OnPostShow = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:4
 Label = FontString {
 }
 BGAtlas = Texture {
 }
 SetAlertContainer = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:12
 SetExternallyManagedOutroAnimation = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:28
 hyperlink = "|cff0070dd|Hcurrency:1807:500|h[Recommandation de la cour des Moissonneurs]|h|r"
 ludius_collected = true
 Background = Texture {
 }
 isCurrency = true
 waitAndAnimOut = AnimationGroup {
 }
 glow = Texture {
 }
 RollValue = FontString {
 }
 RatedPvPBackground = Texture {
 }
 lootItem = Frame {
 }
 RollTypeIcon = Texture {
 }
 UpdateTooltip = <function> defined @Interface/FrameXML/AlertFrameSystems.lua:421
 PvPBackground = Texture {
 }
 queue = <table> {
 }
 animIn = AnimationGroup {
 }
 shine = Texture {
 }
 GetAlertContainer = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:16
 alertContainer = AlertFrame {
 }
 OnPostHide = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:8
 ManagesOwnOutroAnimation = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:24
 OnManagedAlertFrameVisibilityChanged = <function> defined @Interface/FrameXML/AlertFrameIntrinsic.lua:20
 ludius_ignoreParentAlphaBeforeFadeOut = false
}
(*temporary) = nil

**Comment by LudiusMaximus** [comment]
So with ElvUI enabled, it happens reliably **every** time you exit the AFK screen/situation?

**Comment by Darkhibaris** [comment]
Yes. I don't have the problem with Elvui desactivated.

I think I found the problem. It seems the be linked with the AFK situation of DynamicCam.
-->I disable the situation "AFK [Priority: 120]" and it solved the problem with Elvui.

**Comment by LudiusMaximus** [comment]
I just installed ElvUI 13.04 (ElvUI, ElvUI_Libraries, ElvUI_Options) and still cannot reproduce this error. Going in and out of AFK with the DynamicCam situation enabled works just fine. Did you make any ElvUI settings that deviate from its stock settings, which I could try?

**Comment by Darkhibaris** [comment]
Did the same (installed Elvui 13.04) and I haven't the problem anymore. (I was on the 13.02 before).
If you want I can wait for the next Elvui's update to see if the error message comes back, 

After this, I think I will just disable the AFK situation. It's not usefull for me with Elvui.

**Comment by LudiusMaximus** [comment]
Hm, do you still have the 13.02 zip file, so I could reproduce the error? It seems like other addon combinations are triggering it too, but so far no one named the other addons I would have to combine DynamicCam with to evoke it. Unfortunately ElvUI does not seem to have an online archive of their older versions.

**Comment by Darkhibaris** [comment]
Yeah sure! I have the v12.99 too (which was the first I had this problem with (except error)).

To which e-mail address do you want me to send them?

**Comment by LudiusMaximus** [comment]
ludiusmaximus@gmail.com please.

**Comment by LudiusMaximus** [comment]
I think I fixed this with 2.0.5.
Let me know if it pops up again.

**Comment by Darkhibaris** [comment]
Great! Thank you :)
