### ISSUE TITLE
The addon doesn't always detect the situation of the character

### ISSUE THREAD

**Issue by Darkhibaris** [mpstark/DynamicCam#64]
**Version: DynamicCam-2.0.0.zip**

Hi,

When I change the location/situation (ex. mount/dismount), the addon often doesn't detect it. (Situations settings)
--> The configuration of the situation that I have made is therefore not carried out.
![bug_situation_tracking_1](https://user-images.githubusercontent.com/118050158/202032421-98704040-0348-42fe-bec8-954037a12865.jpg)
![bug_situation_tracking_2](https://user-images.githubusercontent.com/118050158/202033959-8da2863d-20f4-4dc7-b76a-09de5a98beb2.jpg)

(Sometimes, it works.)
![bug_situation_tracking_3](https://user-images.githubusercontent.com/118050158/202034280-40016820-bd89-4a96-9586-460fbc173df4.jpg)

I have no error message.

**Comment by LudiusMaximus** [comment]
Hm, I cannot reproduce this.

It looks like your are changing into being mounted without the game event "SPELL_UPDATE_USABLE" or "UNIT_AURA" being fired. These are the two events at which DynamicCam checks if the condition for the Mounted situation is fulfilled.

Maybe you could open the event trace window (typing /eventtrace into the console) and check which events get fired when you mount up and when it is not detected by DynamicCam? Thanks

**Comment by Darkhibaris** [comment]
The problem seems to happen when they are some players in the area.
![eventtrace](https://user-images.githubusercontent.com/118050158/202321568-dbce0869-bc8a-44bc-85f4-7fd5e4670839.jpg)

I tried on a moutain, far away from players and it worked everytime.
![eventtrace2](https://user-images.githubusercontent.com/118050158/202321845-915298f0-8a04-4044-a81e-eca8955f0335.jpg)

**Comment by LudiusMaximus** [comment]
Thank you very much for your investigations!

This looks interesting. In both cases, UNIT_AURA and SPELL_UPDATE_USABLE are fired.
But in the first case (situation not detected) these events come _after_ the PLAYER_MOUNT_DISPLAY_CHANGED event and not before. Maybe the IsMounted() condition is only evaluated to true _after_ the PLAYER_MOUNT_DISPLAY_CHANGED event.

I just tried using PLAYER_MOUNT_DISPLAY_CHANGED as the only event for the "Mounted" situation. And it seems to work just fine. Maybe you want to try this too and check if your problem still persists?

**Comment by Darkhibaris** [comment]
No problem :)

How do I do that?

**Comment by LudiusMaximus** [comment]
![image](https://user-images.githubusercontent.com/4678285/202388853-15a3125f-6ddb-40e6-9f0a-c14e46463046.png)

**Comment by Darkhibaris** [comment]
Sadly, the addon doesn't save PLAYER_MOUNT_DISPLAY_CHANGED. It is always reset by SPELL_UPDATE_USABLE, UNIT_AURA.
![image](https://user-images.githubusercontent.com/118050158/202537573-ea03b9bc-f219-435b-a9d5-e78596f60283.png)

**Comment by Darkhibaris** [comment]
It worked indeed ty!
Maybe i should do this for all other situation, because he addon doesn't detect the other.
![image](https://user-images.githubusercontent.com/118050158/202538370-636cb404-93b4-4563-97a0-6eb597c8f1ef.png)

**Comment by Darkhibaris** [comment]
Nevermind, it's seems it because some are desactivated by default. :)

**Comment by LudiusMaximus** [comment]
Glad it works now! I will make PLAYER_MOUNT_DISPLAY_CHANGED the default event for the "Mounted" situation in the next release.

If you find other situations that are not recognised, please let me know.
