### ISSUE TITLE
DynamicCam's error message after Elvui AFK screen (2)

### ISSUE THREAD

**Issue by Darkhibaris** [mpstark/DynamicCam#66]
Hi again,

[The problem is back](https://github.com/mpstark/DynamicCam/issues/63). (version: DynamicCam-2.0.1.zip)

Since the first pre-patch update from Dragonflight, I have this error message when I go back from the [afk screen from Elvui.](https://www.youtube.com/watch?v=dPZhQszF6ho&ab_channel=DeadlyDag) I can't see my UI. It can be "fix" when I mount or dismount.

![elvui_AFK_screen](https://user-images.githubusercontent.com/118050158/201469581-d34ff9be-569d-4758-a5c9-375044684bfd.jpg)
![error](https://user-images.githubusercontent.com/118050158/201469565-54a08d6b-f1ae-4738-9dfd-ca2eb98d90dc.jpg)
![Mount_for_fix](https://user-images.githubusercontent.com/118050158/201469778-b739744b-7f65-48ee-b782-619c85e6cfc0.jpg)

------------------------------------------------

270x Interface/AddOns/DynamicCam/UiHideModule.lua:445: Usage: self:SetIgnoreParentAlpha(ignore)
[string "=[C]"]: in function `SetIgnoreParentAlpha'
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:445: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:435>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:475: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:472>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:746: in function `HideUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:653: in function `FadeOutUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:1161: in function `ChangeSituation'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:964: in function `EvaluateSituations'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:163: in function <Interface/AddOns/DynamicCam/Core.lua:153>

1x Interface/AddOns/DynamicCam/UiHideModule.lua:446: Usage: self:SetIgnoreParentAlpha(ignore)
[string "=[C]"]: in function SetIgnoreParentAlpha' [string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:446: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:436> [string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:476: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:473> [string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:747: in function HideUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:653: in function FadeOutUI' [string "@Interface/AddOns/DynamicCam/Core.lua"]:1166: in function ChangeSituation'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:969: in function `EvaluateSituations'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:163: in function <Interface/AddOns/DynamicCam/Core.lua:153>

Locals:
(*temporary) = Button {
0 =
ItemName = FontString {
}
OnPostShow = defined @Interface/FrameXML/AlertFrameIntrinsic.lua:4
Label = FontString {
}
BGAtlas = Texture {
}
SetAlertContainer = defined @Interface/FrameXML/AlertFrameIntrinsic.lua:12
SetExternallyManagedOutroAnimation = defined @Interface/FrameXML/AlertFrameIntrinsic.lua:28
hyperlink = "|cff1eff00|Hitem:166846::::::::60:258:::::::::|h[Pièces détachées]|h|r"
ludius_collected = true
Background = Texture {
}
waitAndAnimOut = AnimationGroup {
}
glow = Texture {
}
RollValue = FontString {
}
RatedPvPBackground = Texture {
}
lootItem = Frame {
}
RollTypeIcon = Texture {
}
UpdateTooltip = defined @Interface/FrameXML/AlertFrameSystems.lua:421
PvPBackground = Texture {
}
queue =
{
}
animIn = AnimationGroup {
}
shine = Texture {
}
GetAlertContainer = defined @Interface/FrameXML/AlertFrameIntrinsic.lua:16
alertContainer = AlertFrame {
}
OnPostHide = defined @Interface/FrameXML/AlertFrameIntrinsic.lua:8
ManagesOwnOutroAnimation = defined @Interface/FrameXML/AlertFrameIntrinsic.lua:24
OnManagedAlertFrameVisibilityChanged = defined @Interface/FrameXML/AlertFrameIntrinsic.lua:20
ludius_ignoreParentAlphaBeforeFadeOut = false
}
(*temporary) = nil

**Comment by LudiusMaximus** [comment]
I think I fixed this with 2.0.5.
Let me know if it pops up again.

**Comment by Darkhibaris** [comment]
Great! Thank your for your work :)
