### ISSUE TITLE
2.0.3 (2022-11-18 04:01:22 +0100) prints "be on safe side  FadeInUI 0" +numbers all the time

### ISSUE THREAD

**Issue by Nifelhein** [mpstark/DynamicCam#67]
Hello the latest update (2.0.3 (2022-11-18 04:01:22 +0100) )
prints "be on safe side  FadeInUI 0" +numbers all the time to chat.

let me know if you need any data collected to pinpoint and fix anything.

**Comment by chilblane** [comment]
looks like debug logs were left in

**Comment by eltreum0** [comment]
commit d6f621fa9c355e88bd2f49eed9cb9ce7407462ff on line 714 left the debug print on yes

**Comment by LudiusMaximus** [comment]
Thank you guys! I should have known releasing panic hotfixes at 4 in the morning is no good idea... ;-)
2.0.4 is out now.
