### ISSUE TITLE
Druid flight form triggers error

### ISSUE THREAD

**Issue by derylseale** [mpstark/DynamicCam#68]
I get the following error when assuming flight form:

```
Message: Interface/AddOns/DynamicCam/Core.lua:1190: attempt to index field 'hideUI' (a nil value)
Time: Sun Nov 20 08:33:38 2022
Count: 3
Stack: Interface/AddOns/DynamicCam/Core.lua:1190: attempt to index field 'hideUI' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/DynamicCam/Core.lua"]:1190: in function `ChangeSituation'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:994: in function `EvaluateSituations'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:163: in function <Interface/AddOns/DynamicCam/Core.lua:153>

Locals: 
```
It also seems to recur several times while actually flying.

**Comment by LudiusMaximus** [comment]
Hm, apparently you are using a situation that does not have the "hideUI" configuration entry. This should normally not happen. But I could imagine that this was a custom situation of yours which DynamicCam did not update when changing to 2.0. The easiest way to fix this for you would be to manually copy the "Situation Controls" entries of your custom situation and create a new one with the same entries. Sorry for that.

**Comment by derylseale** [comment]
Yep, that was it!
