### ISSUE TITLE
Fading not working properly with certain addon combinations

### ISSUE THREAD

**Issue by flamestream** [mpstark/DynamicCam#69]
**Steps tp reproduce**

While having only these addons enabled:
- DynamicCam 2.0.4
- Immersion 1.4.14

Trigger an event that fades out the UI (i.e. /afk for many configs). Then notice that the following UI components are not fading out but immediately dissapear after a while
- Minimap
- Quest log

This was noticed as I was trying to reproduce the current hot bug. These two components are the same one that stay visible when the addon would bug out, and be unable to fade back in by pressing the esc button, etc. (Though it seems that people have found out a workaround by mounting up). Hopefully this will give you a hint about where the issue lies.

**Comment by LudiusMaximus** [comment]
Are you still getting this with the newest version? If so, please re-open.
Thanks for reporting!
