### ISSUE TITLE
Hide UI after fade hides Immersion addon UI

### ISSUE THREAD

**Issue by Jofairden** [Mpstark/DynamicCam#7]
Not sure if intended, but _could_ be a bug. I'm not entirely sure what the hide feature is for, I suppose for elements that won't fade or something? In that case it's probably fine. Thought I'd report.

**Comment by Mpstark** [comment]
This is intended, all elements of the UI are faded out. Immersion provides it's own features for fading the UI if you would like to fade everything except for the Immersion frames.

**Comment by Jofairden** [comment]
Alright thanks for letting me know :)
