### ISSUE TITLE
Dragon Riding Mounts aren't Flying Mounts?

### ISSUE THREAD

**Issue by angry-stranger** [mpstark/DynamicCam#71]
I'm trying to make a condition to zoom out when on a flying mount using isFlying() but it doesn't seem to work on dragon riding mounts. Is there a different API for them? I can't find one.

**Comment by LudiusMaximus** [comment]
IsFlying() works on dragon riding mounts as well. If you want to know whether you are on a dragon riding mount, it gets a bit more complicated. The next release of DynamicCam will have a "Dragon Riding" and "Dragon Riding (flying)" situaiton included.
