### ISSUE TITLE
10.0.1 change.

### ISSUE THREAD

**Issue by griddark** [mpstark/DynamicCam#74]
Grabbed from buggrabber.

1x DynamicCam/UiHideModule.lua:336: hooksecurefunc(): AddBarFromTemplate is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@DynamicCam/UiHideModule.lua"]:336: in main chunk

**Comment by Mewohkie** [comment]
Date: 2023-05-03 22:14:15
ID: -3
Error occured in: Global
Count: 1

Message: Interface/AddOns/DynamicCam/UiHideModule.lua line 336:
   hooksecurefunc(): AddBarFromTemplate is not a function

Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:336: in main chunk
Locals:

AddOns:
  Swatter, v9.1.BETA.5.11 (OneMawTime)
  AlterCurrencies, v0.1
  Auctioneer, v9.1.BETA.5.11 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.11 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.11 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.11 (OneMawTime)
  BagBrother, v
  Bagnon, v10.0.16
  CandyBuckets, v10.0.5.230128
  DBMCore, v35c800b
  DBMStatusBarTimers, v35c800b
  DBMVPVEM, vd743100
  Details, v#Details.DF.Wrath.10.0.7.10737.148-53-g3bc8ba7
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DynamicCam, v2.1.0
  Immersion, v1.4.22
  ImmersionExtraFade, v1.16.0
  SlideBar, v9.1.BETA.5.11 (OneMawTime)
  Stubby, v9.1.BETA.5.11 (OneMawTime)
  BlizRuntimeLib_enUS v10.1.0.100100 <none>
  (ck=31c)

**Comment by LudiusMaximus** [comment]
Thank you. Just released a new version with a fix.
