### ISSUE TITLE
Suggestion: Add interaction for questframe interaction

### ISSUE THREAD

**Issue by nihil8** [mpstark/DynamicCam#79]
I can't figure out how to only apply my dynamic cam npc interactions for only quest givers, I've messed around with the situation controls but it won't work to how I want it. I only want to fade and zoom my UI for when i'm talking to people with the QuestFrame or even GossipFrame. Maybe add a situation for that? Or maybe someone can help me.

**Comment by LudiusMaximus** [comment]
You could go to the "Situation Controls" ->"Initialisation" script of the NPC Interaction situation and remove the frames corresponding to NPCs where you do not want the situation to trigger.
