### ISSUE TITLE
Fade UI also hides vendor UI on NPC Interaction

### ISSUE THREAD

**Issue by Jofairden** [Mpstark/DynamicCam#8]
Title. Is that intended? It seems a bit odd, maybe it would be cool if a condition parameter was added so that you wouldn't trigger the fade and hide the vendors UI? Note I do not have Hide UI after fade toggled on.

I have removed the MERCHANT_SHOW, MERCHANT_CLOSED events, however the behavior still triggers. If it matters, the NPC is Chad FIllmore in Western Plaguelands

**Comment by Jofairden** [comment]
For now I've created my own custom situation for quest giver, however it doesnt seem to trigger at all:
`QUEST_COMPLETE, QUEST_DETAIL, QUEST_FINISHED, QUEST_GREETING, QUEST_PROGRESS`

**Comment by Mpstark** [comment]
Fade UI hides the entire UI, this is intended behavior. The way that this is accomplished is by fading the alpha on UIParent, which fades all of it's children, which is all of the UI.

**Comment by Jofairden** [comment]
Alright makes sense. Was just making sure.
