### ISSUE TITLE
QuestFrame to hide UI elv

### ISSUE THREAD

**Issue by Gallegotroll** [mpstark/DynamicCam#83]
Hello, i just discovered this addon and it's cool asf, im trying to configure it with elvui but i cant find the frame name of the quest tracker, also tried with /fstack but maybe the name dont match, so the quest tracker still off when dynamic hide's the ui on different scenarios..

Here are the attribute:
https://i.postimg.cc/bvqTQWNN/Captura-de-pantalla-2023-09-14-131545.png

Thanks in advance and congratz for the addon, it's a fcking crazy work.

**Comment by LudiusMaximus** [comment]
Thanks for your kind words! Glad you like DynamicCam so far. :-)
Regarding the frame name of the quest tracker: Have you tried "ObjectiveTrackerBlocksFrame" as the name? Have you also tried to find the topmost parent of all the quest tracker frames? You can jump one parent up using the top left arrow-up in the Frame Attributes window shown in your screenshot.
