### ISSUE TITLE
Dragonriding (Flying) Fade Out UI error only when Immersion enabled and "Keep additional frames" is ticked

### ISSUE THREAD

**Issue by Flashychunk** [mpstark/DynamicCam#87]
Hi there,

Love your addon, i've been trying to get fade out UI to work when keeping certain UI elements. 

I've noticed that its perfectly fine without Immersion enabled or any dialog changing addon, all the Excluded UI elements section works.

But with Immersion and DynamicCam only being enabled, it causes there to be countless errors when "Keep Additional Frames" is enabled but the frame box is blank. Even with specific frames the errors are the same.

This is the lua error i get, wondered if there is any guidance around this, as I'm just trying to enable in the "Keep Additional Frames" section SuperTrackedFrame (World indicator pin) while flying. 

>Message: Interface/AddOns/DynamicCam/UiHideModule.lua:649: table index is nil
Time: Mon Nov 20 20:02:23 2023
Count: 831
Stack: Interface/AddOns/DynamicCam/UiHideModule.lua:649: table index is nil
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:649: in function <Interface/AddOns/DynamicCam/UiHideModule.lua:623>
[string "@Interface/AddOns/DynamicCam/UiHideModule.lua"]:978: in function `HideUI'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:546: in function `FadeOutUI'
[string "@Interface/AddOns/DynamicCam/SituationManager.lua"]:620: in function `ChangeSituation'
[string "@Interface/AddOns/DynamicCam/SituationManager.lua"]:852: in function `EvaluateSituations'
[string "@Interface/AddOns/DynamicCam/Core.lua"]:97: in function <Interface/AddOns/DynamicCam/Core.lua:90>
Locals: frame = GossipFrame {
 0 = <userdata>
 SetInteractionIsContinuing = <function> defined @Interface/FrameXML/GossipFrameShared.lua:225
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:102
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:98
 tutorialButtons = <table> {
 }
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:84
 OnShow = <function> defined @Interface/FrameXML/GossipFrameShared.lua:176
 AvailableQuestButtonInit = <function> defined @Interface/FrameXML/GossipFrameShared.lua:129
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 ludius_alreadyOnIt = "DynamicCam"
 HandleShow = <function> defined @Interface/FrameXML/GossipFrame.lua:54
 FriendshipStatusBar = StatusBar {
 }
 GreetingPanel = Frame {
 }
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 SetTitleOffsets = <function> defined @Interface/SharedXML/PortraitFrame.lua:54
 Inset = GossipFrameInset {
 }
 CloseButton = GossipFrameCloseButton {
 }
 TopTileStreaks = Texture {
 }
 SetGossipTitle = <function> defined @Interface/FrameXML/GossipFrameShared.lua:300
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:67
 layoutType = "PortraitFrameTemplate"
 TitleContainer = Frame {
 }
 PortraitContainer = Frame {
 }
 SetFrameLevelsFromBaseLevel = <function> defined @Interface/SharedXML/PortraitFrame.lua:120
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:80
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:88
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:76
 Background = Texture {
 }
 Bg = GossipFrameBg {
 }
 SetPortraitToClassIcon = <function> defined @Interface/SharedXML/PortraitFrame.lua:92
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:63
 UpdateScrollBox = <function> defined @Interface/FrameXML/GossipFrameShared.lua:136
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/FrameXML/GossipFrame.lua:49
 OnHide = <function> defined @Interface/FrameXML/GossipFrameShared.lua:183
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:72
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:106
 Update = <function> defined @Interface/FrameXML/GossipFrameShared.lua:247
 SortOrder = <function> defined @Interface/FrameXML/GossipFrame.lua:89
 HandleHide = <function> defined @Interface/FrameXML/GossipFrameShared.lua:218
 SelectGossipOption = <function> defined @Interface/FrameXML/GossipFrameShared.lua:230
 OnEvent = <function> defined @Interface/FrameXML/GossipFrame.lua:73
 SetGossipTutorialMode = <function> defined @Interface/FrameXML/GossipFrame.lua:79
 GetBackgroundTexture = <function> defined @Interface/FrameXML/GossipFrame.lua:62
 GetTutorialButtons = <function> defined @Interface/FrameXML/GossipFrame.lua

**Comment by LudiusMaximus** [comment]
Thank you very much! Fixed with version 2.5.3.
