### ISSUE TITLE
New bug with the Classic.

### ISSUE THREAD

**Issue by HayanShiro** [mpstark/DynamicCam#88]
Happens when using the "Rotating" and "Fading UI" function.
"Rotating" doesn't rotate the camera at all. (AFK, Hearting state)

1927x DynamicCam/UiHideModule.lua:649: table index is nil
[string "@DynamicCam/UiHideModule.lua"]:649: in function <DynamicCam/UiHideModule.lua:623>
[string "@DynamicCam/UiHideModule.lua"]:908: in function `HideUI'
[string "@DynamicCam/Core.lua"]:546: in function `FadeOutUI'
[string "@DynamicCam/SituationManager.lua"]:620: in function `ChangeSituation'
[string "@DynamicCam/SituationManager.lua"]:852: in function `EvaluateSituations'
[string "@DynamicCam/Core.lua"]:97: in function <DynamicCam/Core.lua:90>

Locals:
frame = FramerateLabel {
 0 = <userdata>
 ludius_alreadyOnIt = "DynamicCam"
}
duration = 1
targetIgnoreParentAlpha = true
targetAlpha = 0.500000
currentParent = nil
(*temporary) = <table> {
  = true
}
(*temporary) = WorldFrame {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "table index is nil"
folderName = "DynamicCam"
UIFrameFadeRemoveFrame = <function> defined @DynamicCam/UiHideModule.lua:200
keepDefaultHiddenFramesAsParent = <table> {
  = true
}
InCombatLockdown = <function> defined =[C]:-1
ConditionalHide = <function> defined @DynamicCam/UiHideModule.lua:428
SetMouseOverAlpha = <function> defined @DynamicCam/UiHideModule.lua:294
ConditionalSetIgnoreParentAlpha = <function> defined @DynamicCam/UiHideModule.lua:537
UIFrameFade = <function> defined @DynamicCam/UiHideModule.lua:261

**Comment by LudiusMaximus** [comment]
Thank you very much! Fixed with version 2.5.3.
