### ISSUE TITLE
adding ExtraActionBarFrame to "custom frames to keep" causes Interface/AddOns/DynamicCam/UiHideModule.lua:702: attempt to index a nil value

### ISSUE THREAD

**Issue by ScottIngram** [mpstark/DynamicCam#91]
For the dragon riding situation, I added a Situation Action: Fade Out UI with "custom frames to keep" that included ExtraActionBarFrame.  

Interface/AddOns/DynamicCam/UiHideModule.lua:702

My Fix:
```
      local parent = frame:GetParent()
      fadeInfo.startAlpha = parent and parent:GetAlpha() or 1

```
p.s. my complete list at the moment is:
DR_STATUS_BAR, TomTomCrazyArrow, ObjectiveTrackerUIWidgetContainer, TalkingHeadFrame, UIErrorsFrame, ExtraActionBarFrame, WeakAurasFrame, RaidBossEmoteFrame, EventToastManagerFrame

**Comment by LudiusMaximus** [comment]
Fixed with @ScottIngram's pull request. Thanks again! :-)
