### ISSUE TITLE
Vertical camera adjustment

### ISSUE THREAD

**Issue by RavenTsoni** [mpstark/DynamicCam#97]
Hi, I'd like to know where I can find the lines for the vertical camera adjustment, and if it's possible to modify it?
Thank you so much,all for your addons and your work. ♥

**Comment by LudiusMaximus** [comment]
Hello. DynamicCam only sets the value of the cvar "test_cameraDynamicPitch" which controls the vertical camera adjustment. How the game engine is reacting to this variable cannot be changed by an addon.
