### ISSUE TITLE
Trade, NPC interaction.

### ISSUE THREAD

**Issue by Maravelll** [mpstark/DynamicCam#98]
Hi, sorry for my bad english.

You see, I`m trying to create a situation when I interact whit a merchant npc. The thing is that I want to keep visibe my inventory while im buying or selling. 

I tried using the /fstack command to find the frame name of my bags but no succes.

There is a way i can do it?

I will left you the pics. 

Thankyou for any help.
![WoWScrnShot_061824_042302](https://github.com/mpstark/DynamicCam/assets/173142815/e884e97e-7a5a-4ff7-b6c3-48d1aa5515b1)
![WoWScrnShot_061824_042336](https://github.com/mpstark/DynamicCam/assets/173142815/da626080-78c6-40a5-87bd-1369cb5a4bfa)
![WoWScrnShot_061824_0423363](https://github.com/mpstark/DynamicCam/assets/173142815/561523d2-c693-4cff-8496-061743e1d3ea)

**Comment by LudiusMaximus** [comment]
Hi! It looks like you are using Bagnon (like me). /fstack tells me the frame is called BagnonInventory1. Have you tried this?

**Comment by Maravelll** [comment]
Oh! It works! Great! Thank you! How did you you found the name? I read all the windows in /fstack and nothing works. Y try many names and words. Thank you!

Its a great addon. The best in my opinion. ;D

**Comment by LudiusMaximus** [comment]
Thanks a lot for your kind words! A little tip for figuring out the names of frames is to press the CTRL key while you are in /fstack mode. This opens another window with which you can highlight or hide frames and browse through parent/child-frames. That's how I figured it was BagnonInventory1. Have fun! :-)
